- name: Configure EdgeOS router
  hosts: myhosts
  roles:
    - common
    - networks
    - firewall
    - save

    # - name: Ping my hosts
    #   ansible.builtin.ping:

    # - name: Print message
    #   ansible.builtin.debug:
    #     msg: Hello world

    #  - name: test command
    #    ansible.builtin.command: echo "test"

    # - name: test command 2
      # ansible.builtin.shell:
    # - name: test command 3
      # ansible.builtin.script:
        #  cmd: configure_erx.sh

    # set static IP for yr host - 192.168.1.201 
    # connect to router default subnet 192.168.1.1 

    # default setup 
      # keep initial user 
      # change subnet to 192,.168.2.1 

    # get addr via dhcp 

    # unplug / refresh dhcp to get an ip address on a new subnet 

    # change hostname 

    # change LAN subnet 

    # create DHCP servers 

    # create VLANS for each DHCP server 

    # enable vlan aware switching 

    # create firewall rules 


