- name: Install node-exporter on VPC Linodes
  hosts: servers
  become: true
  roles:
    - node_exporter

- name: Deploy monitoring stack
  hosts: servers
  become: true
  vars:
    grafana_admin_password: "{{grafana_password}}"
    grafana_secret_key: "{{grafana_key}}"
    grafana_domain: "grafana.mycompany.com"
    grafana_datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://localhost:9090
        is_default: true
        editable: false
    grafana_plugins:
      - grafana-clock-panel
      - grafana-polystat-panel
  roles:
    - prometheus
    - snmp_exporter
    - grafana

